sudo: required

os: osx

language: node_js

node_js:
  - '9'
  - '8'

cache:
  directories:
    - "node_modules"

script:
  - cd ${TRAVIS_BUILD_DIR}/modules/nodejs-agent && npm install && npm run check && npm link
  - cd ${TRAVIS_BUILD_DIR}/modules/skyapm-egg-require && npm link skyapm.js && npm install && npm run check
